version: 1.0.{build}-{branch}

image:
  - Visual Studio 2015

artifacts:
  - path: build\**\*.tar.gz
    name: camaro

build: off
environment:
  github_release_token:
    secure: q9SRY5uTjG/sTOzS9WYYj4M/oRy7li2dTVQ/77ZxgcCKKVSvnqF3krOPouUEji6l
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
    - nodejs_version: "13"

matrix:
  fast_finish: true

platform:
  - x64
  - ARM

# cache:
#   - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm config set spin false
  - npm i -g node-pre-gyp --production
  - npm install

test_script:
  - npm test

after_test:
  - node-pre-gyp package 2>&1

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: camaro
    auth_token: $(github_release_token)
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true